#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Lester Hedges <lester.hedges@gmail.com>
#

# Check operating system.
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='mac'
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source Gromacs.
source /usr/local/gromacs/bin/GMXRC

# Useful aliases.
if [[ $platform == 'linux' ]]; then
   alias ls='ls --color=auto --group-directories-first'
else
   alias ls='ls -G'
fi
alias ll='ls -lh'
alias lt='ls -ltr'
alias df='df -h'
alias diff='colordiff'
alias ..='cd ..'
alias ...='cd ../..'
alias o=less
alias vi=vim
alias ssh='kitty +kitten ssh'
alias sudo='sudo '
alias zsnes='zsnes -v 20'
alias sdmlame='sdlmame -rompath ~/Games/Emulators/MAME'
alias vmd='vmd -pos 550 180 -size 400 400'
alias xmgrace='xmgrace -xrm "XMgrace*fontList:fixed"'
alias firefox='firefox > /dev/null 2>&1'
alias man='man -P less'
alias adb='/opt/android-sdk/platform-tools/adb'
alias fastboot='/opt/android-sdk/platform-tools/fastboot'
alias e=exit
alias seed='od -vAn -N4 -tu4 < /dev/urandom'
alias mutt='cd ~/Downloads && mutt'
alias pacman='pacman --color auto'
alias pac='aurman'
alias clear="clear && printf '\e[3J'"
alias sloccount='LANG=C sloccount'

alias pac=aurman   # For convenience

# pacmatic needs to be run as root: https://github.com/keenerd/pacmatic/issues/35
alias pacmatic='sudo --preserve-env=pacman_program /usr/bin/pacmatic'

# Downgrade permissions as AUR helpers expect to be run as a non-root user
# $UID is read-only in {ba,z}sh.
alias aurman='pacman_program="sudo -u #$UID /usr/bin/aurman --optimistic_versioning" pacmatic'

alias reboot='systemctl reboot'
alias shutdown='systemctl poweroff'

# Server variables.
bc3='lh17146@bluecrystalp3.bris.ac.uk'
bc4='lh17146@bc4login.acrc.bris.ac.uk'
bp1='lh17146@bp1-login01b.acrc.bris.ac.uk'
bc1='lh17146@bluecryologin1.acrc.bris.ac.uk'
dice='lh17146@gc00.dice.priv'
oci='lester@129.213.139.109'
ocimgt='-i /home/lester/.oci/oci_api_key.pem -A opc@129.213.139.109'
cibod='lester@cibod.acrc.bris.ac.uk'
website='lohedges_lesterhedges@ssh.phx.nearlyfreespeech.net'

# Compiler flag variables.
png=(-I/usr/include/freetype2/ -lpngwriter -lfreetype -lpng)

export SVN_EDITOR=vim

export SAGE_BROWSER="firefox"
export BROWSER=firefox

# Make man pages more readable.
export MANWIDTH=80

# Sire variables.
export SIRE_BIN=${HOME}/sire.app/bin
export SIRE_SRC=${HOME}/Code/Sire
export SIRE_TESTS=${HOME}/Code/SireUnitTests
export SIRE_DONT_PHONEHOME=1
export SIRE_SILENT_PHONEHOME=1

# Fix for VMD 1.9.4
export VMDNOOPTIX=1

export AMBERHOME=/home/lester/sire.app
export CUDA_VISIBLE_DEVICES=0

# Append /usr/local/lib to LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# Handy systemd shortcuts.
if [[ $platform == 'linux' ]]; then
    if ! systemd-notify --booted; then # not using systemd
    start() {
        sudo rc.d start $1
    }

    restart() {
        sudo rc.d restart $1
    }

    stop() {
        sudo rc.d stop $1
    }
    else
    start() {
        sudo systemctl start $1
    }

    restart() {
        sudo systemctl restart $1
    }

    stop() {
        sudo systemctl stop $1
    }

    #enable() {
        #sudo systemctl enable $1
    #}

    status() {
        sudo systemctl status $1
    }

    disable() {
        sudo systemctl disable $1
    }
    fi
fi
